spring:
  datasource:
    url: jdbc:h2:mem:spectrometer_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false   # Disables the JPA open-in-view warning
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

mqtt:
  broker:
    url: tcp://broker.emqx.io:1883
  client:
    id: ghost-rider-spectrometer
  topic: iot/spectrometer/raw

ai:
  server:
    url: http://localhost:5001

logging:
  level:
    com.spectrometer: DEBUG
    org.springframework.integration.mqtt: WARN
